platform :ios, '8.0'
link_with "iMods", "iModsTests"
pod 'Mantle'
pod 'TSMessages'
pod 'ReactiveCocoa'
pod 'AFNetworking'
pod 'Overcoat', '~>2.0'
pod 'Overcoat/PromiseKit', '~>2.0'
pod 'PromiseKit', '~>0.9.17'
pod 'PRHTask@aufflick'
